
return {
    BASE_DIFFICULTY = 0,

    ARCHETYPE = {
        LOCASTE = 0,
        HICASTE = 0,
        CYCASTE = 2,
        NUCASTE = 0,
        EXCASTE = 1,
        CYBERMACHINE = 2,
        DEMIMACHINE = 2,
        NANOMACHINE = 2,
        BIOMACHINE = 2,
        HOLOMACHINE = 2,
        CHIMERA = 1,
        PALEOCHIMERA = 1,
        MACROCELL = 0,
        CHIMERA = 1,
        POLYMERID = 0,
        SILICID = 0,
        ELASTOMERID = 0,
        PROTOCHIMERA = 1,
        
    },

    INTERACTION_RATING = {
        SOPHONT = 1,
        HOSTILE = 2,
        EXISTENTIAL = 3,
        DANGEROUS = 1,     
        HAZARDOUS = 1,
        BENIGN = 0,
        PROBLEMATIC = 0,
        VERMIN = 0,
        AMBIENT = 0,
        DOMESTIC = 0,
        COMPANION = 0,
        VEHICLE = 0,
        CARRIER = 0,
        NOMAD = 0,
        WEAPON = 1,
        MILITARY = 3,
        LABOR = 0,
        SERVANT = 1,
        HUNTER = 0,
        SANITATION = 0,
        PRODUCT = 0,
        VESSEL = 1,
        DEVIANT = 2,
        AVATAR = 3,
        INCURSION = 3,
    },

    SIZE_VARIANT = {
        MCR = 0,
        MNL = 0,
        SML = 0,
        LSR = 0,
        MDM = 1,    
        LRG = 2,
        HGE = 3,
        GNT = 4,
        TTN = 5,
    }
}