local log = _G.log or function(...) end
log("MEGABEAST_RULES: Loading megabeast classification rules.")

local M = {}

-- Structure: M.RULES[SIZE_KEY][RATING_KEY] = "[TAG_TO_ADD]"
-- The calculator will look up a tag based on this nested table.
M.RULES = {
    -- TITANIC creatures
    TTN = {
        EXISTENTIAL = "[ATTACK_TRIGGER:3:3:3]",
        AVATAR = "[GOOD][MEGABEAST][POWER][ATTACK_TRIGGER:0:0:0][BENIGN]",
        INCURSION = "[EVIL][CANOPENDOORS][INTELLIGENT][UNIQUE_DEMON][SUPERNATURAL][SPREAD_EVIL_SPHERES_IF_RULER][EVIL]"
    },
    
    -- GIANT creatures
    GNT = {
        EXISTENTIAL = "[ATTACK_TRIGGER:2:2:2]",
        AVATAR = "[GOOD][SEMIMEGABEAST][POWER][ATTACK_TRIGGER:0:0:0][BENIGN]",
        INCURSION = "[EVIL][DEMON][SUPERNATURAL][LARGE_ROAMING][LARGE_PREDATOR][BIOME:SUBTERRANEAN_CHASM][UNDERGROUND_DEPTH:5:5][SPREAD_EVIL_SPHERES_IF_RULER][EVIL]",
        BENIGN = "[LARGE_ROAMING][NO_UNIT_TYPE_COLOR]",
        PROBLEMATIC = "[LARGE_ROAMING][NO_UNIT_TYPE_COLOR]",
        HAZARDOUS = "[LARGE_ROAMING][NO_UNIT_TYPE_COLOR]",
        DANGEROUS = "[LARGE_ROAMING][NO_UNIT_TYPE_COLOR]",
        VEHICLE = "[NO_UNIT_TYPE_COLOR]",
        NOMAD = "[NO_UNIT_TYPE_COLOR]",
        CARRIER = "[NO_UNIT_TYPE_COLOR]",
        LABOR = "[NO_UNIT_TYPE_COLOR]",
        SERVANT = "[NO_UNIT_TYPE_COLOR]",
        WEAPON = "[NO_UNIT_TYPE_COLOR]",
        HUNTER = "[NO_UNIT_TYPE_COLOR]",
        DOMESTIC = "[NO_UNIT_TYPE_COLOR]",
        SANITATION = "[NO_UNIT_TYPE_COLOR]",
        PRODUCT = "[NO_UNIT_TYPE_COLOR]",
        MILITARY = "[NO_UNIT_TYPE_COLOR]",
        COMPANION = "[NO_UNIT_TYPE_COLOR]"
    },
    
	
    HGE = {
        BENIGN = "[LARGE_ROAMING][NO_UNIT_TYPE_COLOR]",
        PROBLEMATIC = "[LARGE_ROAMING][NO_UNIT_TYPE_COLOR]",
        HAZARDOUS = "[LARGE_ROAMING][NO_UNIT_TYPE_COLOR]",
        DANGEROUS = "[LARGE_ROAMING][NO_UNIT_TYPE_COLOR]",
        VEHICLE = "[NO_UNIT_TYPE_COLOR]",
        NOMAD = "[NO_UNIT_TYPE_COLOR]",
        CARRIER = "[NO_UNIT_TYPE_COLOR]",
        LABOR = "[NO_UNIT_TYPE_COLOR]",
        SERVANT = "[NO_UNIT_TYPE_COLOR]",
        WEAPON = "[NO_UNIT_TYPE_COLOR]",
        HUNTER = "[NO_UNIT_TYPE_COLOR]",
        DOMESTIC = "[NO_UNIT_TYPE_COLOR]",
        SANITATION = "[NO_UNIT_TYPE_COLOR]",
        PRODUCT = "[NO_UNIT_TYPE_COLOR]",
        MILITARY = "[NO_UNIT_TYPE_COLOR]",
        COMPANION = "[NO_UNIT_TYPE_COLOR]"
    },
    
    LRG = {
        BENIGN = "[LARGE_ROAMING][NO_UNIT_TYPE_COLOR]",
        PROBLEMATIC = "[LARGE_ROAMING][NO_UNIT_TYPE_COLOR]",
        HAZARDOUS = "[LARGE_ROAMING][NO_UNIT_TYPE_COLOR]",
        DANGEROUS = "[LARGE_ROAMING][NO_UNIT_TYPE_COLOR]",
        VEHICLE = "[NO_UNIT_TYPE_COLOR]",
        NOMAD = "[NO_UNIT_TYPE_COLOR]",
        CARRIER = "[NO_UNIT_TYPE_COLOR]",
        LABOR = "[NO_UNIT_TYPE_COLOR]",
        SERVANT = "[NO_UNIT_TYPE_COLOR]",
        WEAPON = "[NO_UNIT_TYPE_COLOR]",
        HUNTER = "[NO_UNIT_TYPE_COLOR]",
        DOMESTIC = "[NO_UNIT_TYPE_COLOR]",
        SANITATION = "[NO_UNIT_TYPE_COLOR]",
        PRODUCT = "[NO_UNIT_TYPE_COLOR]",
        MILITARY = "[NO_UNIT_TYPE_COLOR]",
        COMPANION = "[NO_UNIT_TYPE_COLOR]"
    },
    
    MDM = {
        BENIGN = "[LARGE_ROAMING][NO_UNIT_TYPE_COLOR]",
        PROBLEMATIC = "[LARGE_ROAMING][NO_UNIT_TYPE_COLOR]",
        HAZARDOUS = "[LARGE_ROAMING][NO_UNIT_TYPE_COLOR]",
        DANGEROUS = "[LARGE_ROAMING][NO_UNIT_TYPE_COLOR]",
        VEHICLE = "[NO_UNIT_TYPE_COLOR]",
        NOMAD = "[NO_UNIT_TYPE_COLOR]",
        CARRIER = "[NO_UNIT_TYPE_COLOR]",
        LABOR = "[NO_UNIT_TYPE_COLOR]",
        SERVANT = "[NO_UNIT_TYPE_COLOR]",
        WEAPON = "[NO_UNIT_TYPE_COLOR]",
        HUNTER = "[NO_UNIT_TYPE_COLOR]",
        DOMESTIC = "[NO_UNIT_TYPE_COLOR]",
        SANITATION = "[NO_UNIT_TYPE_COLOR]",
        PRODUCT = "[NO_UNIT_TYPE_COLOR]",
        MILITARY = "[NO_UNIT_TYPE_COLOR]",
        COMPANION = "[NO_UNIT_TYPE_COLOR]"
    },
    
    LSR = {
        BENIGN = "[LARGE_ROAMING][NO_UNIT_TYPE_COLOR]",
        PROBLEMATIC = "[LARGE_ROAMING][NO_UNIT_TYPE_COLOR]",
        HAZARDOUS = "[LARGE_ROAMING][NO_UNIT_TYPE_COLOR]",
        DANGEROUS = "[LARGE_ROAMING][NO_UNIT_TYPE_COLOR]",
        VEHICLE = "[NO_UNIT_TYPE_COLOR]",
        NOMAD = "[NO_UNIT_TYPE_COLOR]",
        CARRIER = "[NO_UNIT_TYPE_COLOR]",
        LABOR = "[NO_UNIT_TYPE_COLOR]",
        SERVANT = "[NO_UNIT_TYPE_COLOR]",
        WEAPON = "[NO_UNIT_TYPE_COLOR]",
        HUNTER = "[NO_UNIT_TYPE_COLOR]",
        DOMESTIC = "[NO_UNIT_TYPE_COLOR]",
        SANITATION = "[NO_UNIT_TYPE_COLOR]",
        PRODUCT = "[NO_UNIT_TYPE_COLOR]",
        MILITARY = "[NO_UNIT_TYPE_COLOR]",
        COMPANION = "[NO_UNIT_TYPE_COLOR]"
    },
    
    MCR = {
        VERMIN = "[VERMIN_ROTTER][VERMIN_NOTRAP][VERMIN_EATER][PENETRATEPOWER:1][NO_UNIT_TYPE_COLOR]",
        AMBIENT = "[VERMIN_NOTRAP][NO_UNIT_TYPE_COLOR]"
    },
    
    MNL = {
        VERMIN = "[VERMIN_ROTTER][VERMIN_EATER][PENETRATEPOWER:2][NO_UNIT_TYPE_COLOR]",
        AMBIENT = "[NO_UNIT_TYPE_COLOR]"
    },
    
    SML = {
        VERMIN = "[VERMIN_ROTTER][VERMIN_EATER][PENETRATEPOWER:3][NO_UNIT_TYPE_COLOR]",
        AMBIENT = "[NO_UNIT_TYPE_COLOR]"
    }
}

return M