return {
    -- ============================================================================
    -- CONFIGURATION
    -- ============================================================================
    
    -- The starting value for all skills. 
    -- Final Skill = Base Level + Archetype Mod + Rating Mod + Size Mod
    BASE_LEVEL = 0,

    TRACKED_SKILLS = {
			"BITE",
            "GRASP_STRIKE",
            "STANCE_STRIKE",
            "WRESTLING",
            "DODGING",
            "THROW",
            "RANGED_COMBAT",
            "MELEE_COMBAT",
            "SITUATIONAL_AWARENESS",
            "READING",
            "SWIMMING",
			"DISCIPLINE"
    },

    -- ============================================================================
    -- ARCHETYPE MODIFIERS
    -- Add or subtract from the base level.
    -- ============================================================================
    ARCHETYPE = {
        BIOMACHINE = {
            BITE = 2,
            GRASP_STRIKE = 2,
            STANCE_STRIKE = 2,
            WRESTLING = 2,
            DODGING = 1,
            THROW = 1,
            RANGED_COMBAT = 1,
            MELEE_COMBAT = 1,
            SITUATIONAL_AWARENESS = 1,
            READING = 1,
            SWIMMING = 2,
            DISCIPLINE = 2
        },
        CYCASTE = {
            BITE = 0,
            GRASP_STRIKE = 0,
            STANCE_STRIKE = 0,
            WRESTLING = 0,
            DODGING = 0,
            THROW = 0,
            RANGED_COMBAT = 0,
            MELEE_COMBAT = 0,
            SITUATIONAL_AWARENESS = 2,
            READING = 1,
            SWIMMING = 1,
            DISCIPLINE = 1
        },
        EXCASTE = {
            BITE = 1,
            GRASP_STRIKE = 1,
            STANCE_STRIKE = 1,
            WRESTLING = 1,
            DODGING = 1,
            THROW = 1,
            RANGED_COMBAT = 1,
            MELEE_COMBAT = 1,
            SITUATIONAL_AWARENESS = 1,
            READING = 0,
            SWIMMING = 2,
            DISCIPLINE = 0
        },
        LOCASTE = {
            BITE = 0,
            GRASP_STRIKE = 0,
            STANCE_STRIKE = 0,
            WRESTLING = 0,
            DODGING = 0,
            THROW = 0,
            RANGED_COMBAT = 0,
            MELEE_COMBAT = 0,
            SITUATIONAL_AWARENESS = 1,
            READING = 1,
            SWIMMING = 1,
            DISCIPLINE = 0
        },
        HICASTE = {
            BITE = 0,
            GRASP_STRIKE = 0,
            STANCE_STRIKE = 0,
            WRESTLING = 0,
            DODGING = 0,
            THROW = 0,
            RANGED_COMBAT = 0,
            MELEE_COMBAT = 0,
            SITUATIONAL_AWARENESS = 1,
            READING = 1,
            SWIMMING = 1,
            READING = 3,
            SWIMMING = 1,
            DISCIPLINE = 1
        },
        NUCASTE = {
            BITE = 1,
            GRASP_STRIKE = 1,
            STANCE_STRIKE = 1,
            WRESTLING = 1,
            DODGING = 1,
            THROW = 1,
            RANGED_COMBAT = 1,
            MELEE_COMBAT = 1,
            SITUATIONAL_AWARENESS = 1,
            READING = 1,
            SWIMMING = 1,
            DISCIPLINE = 1
        },
        CYBERMACHINE = {
            BITE = 1,
            GRASP_STRIKE = 1,
            STANCE_STRIKE = 1,
            WRESTLING = 1,
            DODGING = 1,
            THROW = 1,
            RANGED_COMBAT = 2,
            MELEE_COMBAT = 2,
            SITUATIONAL_AWARENESS = 2,
            READING = 3,
            SWIMMING = 0,
            DISCIPLINE = 4
        },
        DEMIMACHINE = {
            BITE = 1,
            GRASP_STRIKE = 1,
            STANCE_STRIKE = 1,
            WRESTLING = 1,
            DODGING = 1,
            THROW = 1,
            RANGED_COMBAT = 1,
            MELEE_COMBAT = 1,
            SITUATIONAL_AWARENESS = 1,
            READING = 1,
            SWIMMING = 1,
            DISCIPLINE = 3
        },
        NANOMACHINE = {
            BITE = 2,
            GRASP_STRIKE = 2,
            STANCE_STRIKE = 2,
            WRESTLING = 2,
            DODGING = 1,
            THROW = 1,
            RANGED_COMBAT = 1,
            MELEE_COMBAT = 1,
            SITUATIONAL_AWARENESS = 1,
            READING = 1,
            SWIMMING = 1,
            DISCIPLINE = 1
        },
        CHIMERA = {
            BITE = 1,
            GRASP_STRIKE = 1,
            STANCE_STRIKE = 1,
            WRESTLING = 0,
            DODGING = 1,
            THROW = 1,
            RANGED_COMBAT = 0,
            MELEE_COMBAT = 0,
            SITUATIONAL_AWARENESS = 1,
            READING = 0,
            SWIMMING = 0,
            DISCIPLINE = 0
        },
        PALEOCHIMERA = {
            BITE = 1,
            GRASP_STRIKE = 1,
            STANCE_STRIKE = 1,
            WRESTLING = 0,
            DODGING = 1,
            THROW = 1,
            RANGED_COMBAT = 0,
            MELEE_COMBAT = 0,
            SITUATIONAL_AWARENESS = 1,
            READING = 0,
            SWIMMING = 0,
            DISCIPLINE = 0
        },
        PROTOCHIMERA = {
            BITE = 0,
            GRASP_STRIKE = 0,
            STANCE_STRIKE = 0,
            WRESTLING = 0,
            DODGING = 0,
            THROW = 0,
            RANGED_COMBAT = 0,
            MELEE_COMBAT = 0,
            SITUATIONAL_AWARENESS = 0,
            READING = 0,
            SWIMMING = 0,
            DISCIPLINE = 0
        },
        MACROCELL = {
            BITE = 0,
            GRASP_STRIKE = 0,
            STANCE_STRIKE = 0,
            WRESTLING = 0,
            DODGING = 0,
            THROW = 0,
            RANGED_COMBAT = 0,
            MELEE_COMBAT = 0,
            SITUATIONAL_AWARENESS = 0,
            READING = 0,
            SWIMMING = 1,
            DISCIPLINE = 0
        },
        POLYMERID = {
            BITE = 0,
            GRASP_STRIKE = 0,
            STANCE_STRIKE = 0,
            WRESTLING = 0,
            DODGING = 0,
            THROW = 0,
            RANGED_COMBAT = 0,
            MELEE_COMBAT = 0,
            SITUATIONAL_AWARENESS = 1,
            READING = 0,
            SWIMMING = 1,
            DISCIPLINE = 0
        },
        ELASTOMERID = {
            BITE = 0,
            GRASP_STRIKE = 0,
            STANCE_STRIKE = 0,
            WRESTLING = 0,
            DODGING = 0,
            THROW = 0,
            RANGED_COMBAT = 0,
            MELEE_COMBAT = 0,
            SITUATIONAL_AWARENESS = 1,
            READING = 0,
            SWIMMING = 1,
            DISCIPLINE = 0
        },
        SILICID = {
            BITE = 0,
            GRASP_STRIKE = 0,
            STANCE_STRIKE = 0,
            WRESTLING = 0,
            DODGING = 0,
            THROW = 0,
            RANGED_COMBAT = 0,
            MELEE_COMBAT = 0,
            SITUATIONAL_AWARENESS = 1,
            READING = 0,
            SWIMMING = 1,
            DISCIPLINE = 0
        },
    },

    -- ============================================================================
    -- RATING MODIFIERS
    -- Based on interaction rating (e.g. HOSTILE, MILITARY)
    -- ============================================================================
    RATING = {
        MILITARY = {
            BITE = 2,
            GRASP_STRIKE = 2,
            STANCE_STRIKE = 2,
            WRESTLING = 1,
            DODGING = 1,
            THROW = 1,
            RANGED_COMBAT = 1,
            MELEE_COMBAT = 1,
            SITUATIONAL_AWARENESS = 1,
            READING = 0,
            SWIMMING = 1,
            DISCIPLINE = 3
        },
        WEAPON = {
            BITE = 1,
            GRASP_STRIKE = 1,
            STANCE_STRIKE = 1,
            WRESTLING = 1,
            DODGING = 1,
            THROW = 1,
            RANGED_COMBAT = 1,
            MELEE_COMBAT = 1,
            SITUATIONAL_AWARENESS = 1,
            READING = 0,
            SWIMMING = 1,
            DISCIPLINE = 2
        },
        HOSTILE = {
            BITE = 1,
            GRASP_STRIKE = 1,
            STANCE_STRIKE = 1,
            WRESTLING = 1,
            DODGING = 1,
            THROW = 1,
            RANGED_COMBAT = 1,
            MELEE_COMBAT = 1,
            SITUATIONAL_AWARENESS = 1,
            READING = 0,
            SWIMMING = 1,
            DISCIPLINE = 3
        },
        BENIGN = {
            BITE = -2,
            GRASP_STRIKE = -2,
            STANCE_STRIKE = -2,
            WRESTLING = -2,
            DODGING = 0,
            THROW = -2,
            RANGED_COMBAT = -2,
            MELEE_COMBAT = -2,
            SITUATIONAL_AWARENESS = 1,
            READING = 0,
            SWIMMING = 0,
            DISCIPLINE = 0
        },
        SOPHONT = {
            BITE = 0,
            GRASP_STRIKE = 0,
            STANCE_STRIKE = 0,
            WRESTLING = 0,
            DODGING = 0,
            THROW = 0,
            RANGED_COMBAT = 0,
            MELEE_COMBAT = 0,
            SITUATIONAL_AWARENESS = 0,
            READING = 0,
            SWIMMING = 0,
            DISCIPLINE = 1
		},
        EXISTENTIAL = {
            BITE = 2,
            GRASP_STRIKE = 2,
            STANCE_STRIKE = 2,
            WRESTLING = 2,
            DODGING = 2,
            THROW = 2,
            RANGED_COMBAT = 0,
            MELEE_COMBAT = 0,
            SITUATIONAL_AWARENESS = 3,
            READING = 0,
            SWIMMING = 0,
            DISCIPLINE = 3
		},
        DANGEROUS = {
            BITE = 1,
            GRASP_STRIKE = 1,
            STANCE_STRIKE = 1,
            WRESTLING = 1,
            DODGING = 1,
            THROW = 1,
            RANGED_COMBAT = 1,
            MELEE_COMBAT = 1,
            SITUATIONAL_AWARENESS = 1,
            READING = 0,
            SWIMMING = 1,
            DISCIPLINE = 0
		},
        HAZARDOUS = {
            BITE = 1,
            GRASP_STRIKE = 1,
            STANCE_STRIKE = 1,
            WRESTLING = 1,
            DODGING = 0,
            THROW = 1,
            RANGED_COMBAT = 1,
            MELEE_COMBAT = 1,
            SITUATIONAL_AWARENESS = 1,
            READING = 0,
            SWIMMING = 1,
            DISCIPLINE = 0
		},
        PROBLEMATIC = {
            BITE = 1,
            GRASP_STRIKE = 1,
            STANCE_STRIKE = 1,
            WRESTLING = 1,
            DODGING = 2,
            THROW = 1,
            RANGED_COMBAT = 1,
            MELEE_COMBAT = 1,
            SITUATIONAL_AWARENESS = 1,
            READING = 0,
            SWIMMING = 1,
            DISCIPLINE = 0
		},
        VERMIN = {	
            BITE = -5,
            GRASP_STRIKE = -5,
            STANCE_STRIKE = -5,
            WRESTLING = -5,
            DODGING = -5,
            THROW = -5,
            RANGED_COMBAT = -5,
            MELEE_COMBAT = -5,
            SITUATIONAL_AWARENESS = -5,
            READING = -5,
            SWIMMING = -5,
            DISCIPLINE = 0
		},
        AMBIENT = {
            BITE = -5,
            GRASP_STRIKE = -5,
            STANCE_STRIKE = -5,
            WRESTLING = -5,
            DODGING = -5,
            THROW = -5,
            RANGED_COMBAT = -5,
            MELEE_COMBAT = -5,
            SITUATIONAL_AWARENESS = -5,
            READING = -5,
            SWIMMING = -5,
            DISCIPLINE = 0
		},
        DOMESTIC = {
            BITE = -5,
            GRASP_STRIKE = -5,
            STANCE_STRIKE = -5,
            WRESTLING = -5,
            DODGING = -5,
            THROW = -5,
            RANGED_COMBAT = -5,
            MELEE_COMBAT = -5,
            SITUATIONAL_AWARENESS = -5,
            READING = -5,
            SWIMMING = -5,
            DISCIPLINE = 0
		},
        COMPANION = {
            BITE = -5,
            GRASP_STRIKE = -5,
            STANCE_STRIKE = -5,
            WRESTLING = -5,
            DODGING = -5,
            THROW = -5,
            RANGED_COMBAT = -5,
            MELEE_COMBAT = -5,
            SITUATIONAL_AWARENESS = -5,
            READING = -5,
            SWIMMING = -5,
            DISCIPLINE = 0
		},
        VEHICLE = {
            BITE = -5,
            GRASP_STRIKE = -5,
            STANCE_STRIKE = -5,
            WRESTLING = -5,
            DODGING = 3,
            THROW = -5,
            RANGED_COMBAT = -5,
            MELEE_COMBAT = -5,
            SITUATIONAL_AWARENESS = -5,
            READING = -5,
            SWIMMING = -5,
            DISCIPLINE = 5
		},
        CARRIER = {
            BITE = -5,
            GRASP_STRIKE = -5,
            STANCE_STRIKE = -5,
            WRESTLING = -5,
            DODGING = 0,
            THROW = -5,
            RANGED_COMBAT = -5,
            MELEE_COMBAT = -5,
            SITUATIONAL_AWARENESS = -5,
            READING = -5,
            SWIMMING = -5,
            DISCIPLINE = 5
		},
        NOMAD = {
            BITE = -5,
            GRASP_STRIKE = -5,
            STANCE_STRIKE = -5,
            WRESTLING = -5,
            DODGING = 1,
            THROW = -5,
            RANGED_COMBAT = -5,
            MELEE_COMBAT = -5,
            SITUATIONAL_AWARENESS = -5,
            READING = -5,
            SWIMMING = -5,
            DISCIPLINE = 5
		},
        SERVANT = {
            BITE = 0,
            GRASP_STRIKE = 0,
            STANCE_STRIKE = 0,
            WRESTLING = 0,
            DODGING = 0,
            THROW = 0,
            RANGED_COMBAT = 0,
            MELEE_COMBAT = 0,
            SITUATIONAL_AWARENESS = 0,
            READING = 0,
            SWIMMING = 0,
            DISCIPLINE = 3
		},
        HUNTER = {
            BITE = 1,
            GRASP_STRIKE = 1,
            STANCE_STRIKE = 1,
            WRESTLING = 1,
            DODGING = 1,
            THROW = 1,
            RANGED_COMBAT = 1,
            MELEE_COMBAT = 1,
            SITUATIONAL_AWARENESS = 1,
            READING = 0,
            SWIMMING = 1,
            DISCIPLINE = 1
		},
        SANITATION = {
            BITE = -5,
            GRASP_STRIKE = -5,
            STANCE_STRIKE = -5,
            WRESTLING = -5,
            DODGING = 1,
            THROW = -5,
            RANGED_COMBAT = -5,
            MELEE_COMBAT = -5,
            SITUATIONAL_AWARENESS = -5,
            READING = -5,
            SWIMMING = -5,
            DISCIPLINE = 0
		},
        PRODUCT = {
            BITE = -5,
            GRASP_STRIKE = -5,
            STANCE_STRIKE = -5,
            WRESTLING = -5,
            DODGING = 1,
            THROW = -5,
            RANGED_COMBAT = -5,
            MELEE_COMBAT = -5,
            SITUATIONAL_AWARENESS = -5,
            READING = -5,
            SWIMMING = -5,
            DISCIPLINE = 0
		},
        VESSEL = {
            BITE = 0,
            GRASP_STRIKE = 0,
            STANCE_STRIKE = 0,
            WRESTLING = 0,
            DODGING = 0,
            THROW = 0,
            RANGED_COMBAT = 0,
            MELEE_COMBAT = 0,
            SITUATIONAL_AWARENESS = 0,
            READING = 0,
            SWIMMING = 0,
            DISCIPLINE = 6
			},
        DEVIANT = {
            BITE = 0,
            GRASP_STRIKE = 0,
            STANCE_STRIKE = 0,
            WRESTLING = 0,
            DODGING = 0,
            THROW = 0,
            RANGED_COMBAT = 0,
            MELEE_COMBAT = 0,
            SITUATIONAL_AWARENESS = 0,
            READING = 0,
            SWIMMING = 0,
            DISCIPLINE = 2
			},
        AVATAR = {
            BITE = 2,
            GRASP_STRIKE = 2,
            STANCE_STRIKE = 2,
            WRESTLING = 2,
            DODGING = 2,
            THROW = 2,
            RANGED_COMBAT = 3,
            MELEE_COMBAT = 3,
            SITUATIONAL_AWARENESS = 3,
            READING = 1,
            SWIMMING = 3,
            DISCIPLINE = 5
			},
        INCURSION = {
            BITE = 2,
            GRASP_STRIKE = 2,
            STANCE_STRIKE = 2,
            WRESTLING = 2,
            DODGING = 2,
            THROW = 2,
            RANGED_COMBAT = 3,
            MELEE_COMBAT = 3,
            SITUATIONAL_AWARENESS = 3,
            READING = 1,
            SWIMMING = 3,
            DISCIPLINE = 6
			},
    },

    -- ============================================================================
    -- SIZE MODIFIERS
    -- ============================================================================
    SIZE = {
        MCR = { DODGING = 0 },
        MNL = { DODGING = 0 },
        SML = { DODGING = 2 },
        LSR = { 
				DODGING = 1,
				SITUATIONAL_AWARENESS = 1
			  },
        MDM = { DODGING = 0 }, 
        LRG = { DODGING = -1 },
        HGE = { DODGING = -2 },
        GNT = { DODGING = -3 },
        TTN = {
            DODGING = -4, 
            MELEE_COMBAT = 2 
        },
    }
}