

local common_data = {}




common_data.arrivaltypes = {
    { value = [[
[ACTIVE_SEASON:SUMMER]
]], weight = 1 },
    { value = [[
[ACTIVE_SEASON:SPRING]
]], weight = 1 },
    { value = [[
[ACTIVE_SEASON:AUTUMN]
]], weight = 1 },
    { value = [[
[ACTIVE_SEASON:WINTER]
]], weight = 1 }
}

common_data.languages_human = {
    { value = [[
[TRANSLATION:GEN_LOCANT_1]
]], weight = 2 },
    { value = [[
[TRANSLATION:GEN_LOCANT_2]
]], weight = 1 },
    { value = [[
[TRANSLATION:GEN_LOCANT_3]
]], weight = 1 },
    { value = [[
[TRANSLATION:GEN_LOCANT_4]
]], weight = 1 },
    { value = [[
[TRANSLATION:GEN_LOCANT_5]
]], weight = 1 },
    { value = [[
[TRANSLATION:GEN_LOCANT_6]
]], weight = 1 }
}

common_data.languages_imperial = {
    { value = [[
[TRANSLATION:GEN_HICANT]
]], weight = 100 }
}

common_data.languages_transitional = {
    { value = [[
[TRANSLATION:GEN_EXCANT_1]
]], weight = 1 },
    { value = [[
[TRANSLATION:GEN_EXCANT_2]
]], weight = 1 },
    { value = [[
[TRANSLATION:GEN_EXCANT_3]
]], weight = 1 }
}

common_data.languages_posthuman = {
    { value = [[
[TRANSLATION:GEN_POSTCANT]
]], weight = 3 }
}

common_data.languages_myriad = {
    { value = [[
[TRANSLATION:GEN_ENDCANT]
]], weight = 3 }
}

common_data.languages_tribal = {
    { value = [[
[TRANSLATION:GEN_UNCANT_1]
]], weight = 1 },
    { value = [[
[TRANSLATION:GEN_UNCANT_2]
]], weight = 1 },
    { value = [[
[TRANSLATION:GEN_UNCANT_3]
]], weight = 1 }
}

common_data.bandits_medium = {
    { value = [[
[BANDITRY:5]
]], weight = 6 },
    { value = [[
[BANDITRY:10]
]], weight = 5 },
    { value = [[
[BANDITRY:20]
]], weight = 4 },
    { value = [[
[BANDITRY:30]
]], weight = 3 },
    { value = [[
[BANDITRY:40]
]], weight = 2 },
    { value = [[
[BANDITRY:50]
]], weight = 1 }
}

common_data.bandits_high = {
    { value = [[
[BANDITRY:10]
]], weight = 9 },
    { value = [[
[BANDITRY:20]
]], weight = 8 },
    { value = [[
[BANDITRY:30]
]], weight = 7 },
    { value = [[
[BANDITRY:40]
]], weight = 6 },
    { value = [[
[BANDITRY:50]
]], weight = 5 },
    { value = [[
[BANDITRY:60]
]], weight = 4 },
    { value = [[
[BANDITRY:70]
]], weight = 3 },
    { value = [[
[BANDITRY:80]
]], weight = 2 },
    { value = [[
[BANDITRY:90]
]], weight = 1 }
}

common_data.bandits_low = {
    { value = [[
[BANDITRY:1]
]], weight = 3 },
    { value = [[
[BANDITRY:5]
]], weight = 2 },
    { value = [[
[BANDITRY:10]
]], weight = 1 }
}

common_data.bandits_lower = {
    { value = [[
[BANDITRY:5]
]], weight = 1 },
    { value = [[
[BANDITRY:15]
]], weight = 1 }
}

common_data.law_serious_order = {
    { value = [[
[ETHIC:KILL_ENTITY_MEMBER:JUSTIFIED_IF_GOOD_REASON]
[ETHIC:KILL_NEUTRAL:JUSTIFIED_IF_GOOD_REASON]
[ETHIC:ASSAULT:JUSTIFIED_IF_GOOD_REASON]
[ETHIC:TREASON:JUSTIFIED_IF_EXTREME_REASON]
[ETHIC:KILL_ENEMY:ACCEPTABLE]
[ETHIC:KILL_ANIMAL:ACCEPTABLE]
[ETHIC:KILL_PLANT:ACCEPTABLE]
]], weight = 1 },
    { value = [[
[ETHIC:KILL_ENTITY_MEMBER:JUSTIFIED_IF_EXTREME_REASON]
[ETHIC:KILL_NEUTRAL:JUSTIFIED_IF_EXTREME_REASON]
[ETHIC:ASSAULT:JUSTIFIED_IF_SELF_DEFENSE]
[ETHIC:TREASON:PUNISH_EXILE]
[ETHIC:KILL_ENEMY:ACCEPTABLE]
[ETHIC:KILL_ANIMAL:ACCEPTABLE]
[ETHIC:KILL_PLANT:ACCEPTABLE]
]], weight = 1 },
    { value = [[
[ETHIC:KILL_ENTITY_MEMBER:JUSTIFIED_IF_SELF_DEFENSE]
[ETHIC:KILL_NEUTRAL:JUSTIFIED_IF_SELF_DEFENSE]
[ETHIC:ASSAULT:JUSTIFIED_IF_SELF_DEFENSE]
[ETHIC:TREASON:PUNISH_CAPITAL]
[ETHIC:KILL_ENEMY:ACCEPTABLE]
[ETHIC:KILL_ANIMAL:ACCEPTABLE]
[ETHIC:KILL_PLANT:ACCEPTABLE]
]], weight = 1 },
    { value = [[
[ETHIC:KILL_ENTITY_MEMBER:ONLY_IF_SANCTIONED]
[ETHIC:KILL_NEUTRAL:ONLY_IF_SANCTIONED]
[ETHIC:ASSAULT:JUSTIFIED_IF_SELF_DEFENSE]
[ETHIC:TREASON:PUNISH_CAPITAL]
[ETHIC:KILL_ENEMY:ACCEPTABLE]
[ETHIC:KILL_ANIMAL:ACCEPTABLE]
[ETHIC:KILL_PLANT:ACCEPTABLE]
]], weight = 1 },
    { value = [[
[ETHIC:KILL_ENTITY_MEMBER:ONLY_IF_SANCTIONED]
[ETHIC:KILL_NEUTRAL:ONLY_IF_SANCTIONED]
[ETHIC:ASSAULT:ONLY_IF_SANCTIONED]
[ETHIC:TREASON:PUNISH_CAPITAL]
[ETHIC:KILL_ENEMY:ACCEPTABLE]
[ETHIC:KILL_ANIMAL:ACCEPTABLE]
[ETHIC:KILL_PLANT:ACCEPTABLE]
]], weight = 1 }
}


common_data.law_serious_chaos = {
    { value = [[
[ETHIC:KILL_ENTITY_MEMBER:JUSTIFIED_IF_GOOD_REASON]
[ETHIC:KILL_NEUTRAL:JUSTIFIED_IF_GOOD_REASON]
[ETHIC:ASSAULT:JUSTIFIED_IF_GOOD_REASON]
[ETHIC:TREASON:JUSTIFIED_IF_NO_REPERCUSSIONS]
[ETHIC:KILL_ENEMY:ACCEPTABLE]
[ETHIC:KILL_ANIMAL:ACCEPTABLE]
[ETHIC:KILL_PLANT:ACCEPTABLE]
]], weight = 1 },
    { value = [[
[ETHIC:KILL_ENTITY_MEMBER:PERSONAL_MATTER]
[ETHIC:KILL_NEUTRAL:PERSONAL_MATTER]
[ETHIC:ASSAULT:PERSONAL_MATTER]
[ETHIC:TREASON:JUSTIFIED_IF_NO_REPERCUSSIONS]
[ETHIC:KILL_ENEMY:ACCEPTABLE]
[ETHIC:KILL_ANIMAL:ACCEPTABLE]
[ETHIC:KILL_PLANT:ACCEPTABLE]
]], weight = 1 },
    { value = [[
[ETHIC:KILL_ENTITY_MEMBER:JUSTIFIED_IF_SELF_DEFENSE]
[ETHIC:KILL_NEUTRAL:JUSTIFIED_IF_SELF_DEFENSE]
[ETHIC:ASSAULT:JUSTIFIED_IF_SELF_DEFENSE]
[ETHIC:TREASON:JUSTIFIED_IF_NO_REPERCUSSIONS]
[ETHIC:TREASON:PUNISH_CAPITAL]
[ETHIC:KILL_ENEMY:ACCEPTABLE]
[ETHIC:KILL_ANIMAL:ACCEPTABLE]
[ETHIC:KILL_PLANT:ACCEPTABLE]
]], weight = 1 },
    { value = [[
[ETHIC:KILL_ENTITY_MEMBER:PERSONAL_MATTER]
[ETHIC:KILL_NEUTRAL:PERSONAL_MATTER]
[ETHIC:ASSAULT:PERSONAL_MATTER]
[ETHIC:TREASON:PUNISH_EXILE]
[ETHIC:KILL_ENEMY:ACCEPTABLE]
[ETHIC:KILL_ANIMAL:ACCEPTABLE]
[ETHIC:KILL_PLANT:ACCEPTABLE]
]], weight = 1 },
    { value = [[
[ETHIC:KILL_ENTITY_MEMBER:JUSTIFIED_IF_SELF_DEFENSE]
[ETHIC:KILL_NEUTRAL:JUSTIFIED_IF_SELF_DEFENSE]
[ETHIC:ASSAULT:JUSTIFIED_IF_SELF_DEFENSE]
[ETHIC:TREASON:PUNISH_EXILE]
[ETHIC:KILL_ENEMY:ACCEPTABLE]
[ETHIC:KILL_ANIMAL:ACCEPTABLE]
[ETHIC:KILL_PLANT:ACCEPTABLE]
]], weight = 1 }
}

common_data.law_petty_order = {
    { value = [[
[ETHIC:LYING:PERSONAL_MATTER]
[ETHIC:THEFT:MISGUIDED]
[ETHIC:TRESPASSING:MISGUIDED]
[ETHIC:VANDALISM:MISGUIDED]
]], weight = 1 },
    { value = [[
[ETHIC:LYING:MISGUIDED]
[ETHIC:THEFT:PUNISH_REPRIMAND]
[ETHIC:TRESPASSING:PUNISH_REPRIMAND]
[ETHIC:VANDALISM:PUNISH_REPRIMAND]
]], weight = 1 },
    { value = [[
[ETHIC:LYING:PUNISH_REPRIMAND]
[ETHIC:THEFT:PUNISH_SERIOUS]
[ETHIC:TRESPASSING:PUNISH_SERIOUS]
[ETHIC:VANDALISM:PUNISH_SERIOUS]
]], weight = 1 }
}

common_data.law_petty_chaos = {
    { value = [[
[ETHIC:LYING:ACCEPTABLE]
[ETHIC:THEFT:ACCEPTABLE]
[ETHIC:TRESPASSING:ACCEPTABLE]
[ETHIC:VANDALISM:ACCEPTABLE]
]], weight = 1 },
    { value = [[
[ETHIC:LYING:PERSONAL_MATTER]
[ETHIC:THEFT:PERSONAL_MATTER]
[ETHIC:TRESPASSING:PERSONAL_MATTER]
[ETHIC:VANDALISM:PERSONAL_MATTER]
]], weight = 1 },
    { value = [[
[ETHIC:LYING:SHUN]
[ETHIC:THEFT:SHUN]
[ETHIC:TRESPASSING:SHUN]
[ETHIC:VANDALISM:SHUN]
]], weight = 1 }
}


common_data.trophys = {
    { value = [[
[ETHIC:MAKE_TROPHY_SAME_RACE:ACCEPTABLE]
[ETHIC:MAKE_TROPHY_SAPIENT:ACCEPTABLE]
[ETHIC:MAKE_TROPHY_ANIMAL:ACCEPTABLE]
]], weight = 1 },
    { value = [[
[ETHIC:MAKE_TROPHY_SAME_RACE:MISGUIDED]
[ETHIC:MAKE_TROPHY_SAPIENT:ACCEPTABLE]
[ETHIC:MAKE_TROPHY_ANIMAL:ACCEPTABLE]
]], weight = 1 },
    { value = [[
[ETHIC:MAKE_TROPHY_SAME_RACE:APPALLING]
[ETHIC:MAKE_TROPHY_SAPIENT:ACCEPTABLE]
[ETHIC:MAKE_TROPHY_ANIMAL:ACCEPTABLE]
]], weight = 1 },
    { value = [[
[ETHIC:MAKE_TROPHY_SAME_RACE:APPALLING]
[ETHIC:MAKE_TROPHY_SAPIENT:MISGUIDED]
[ETHIC:MAKE_TROPHY_ANIMAL:ACCEPTABLE]
]], weight = 1 },
    { value = [[
[ETHIC:MAKE_TROPHY_SAME_RACE:APPALLING]
[ETHIC:MAKE_TROPHY_SAPIENT:APPALLING]
[ETHIC:MAKE_TROPHY_ANIMAL:ACCEPTABLE]
]], weight = 1 },
    { value = [[
[ETHIC:MAKE_TROPHY_SAME_RACE:REQUIRED]
[ETHIC:MAKE_TROPHY_SAPIENT:ACCEPTABLE]
[ETHIC:MAKE_TROPHY_ANIMAL:ACCEPTABLE]
]], weight = 1 },
    { value = [[
[ETHIC:MAKE_TROPHY_SAME_RACE:REQUIRED]
[ETHIC:MAKE_TROPHY_SAPIENT:REQUIRED]
[ETHIC:MAKE_TROPHY_ANIMAL:ACCEPTABLE]
]], weight = 1 }
}

common_data.slaves = {
    { value = [[
[ETHIC:SLAVERY:ACCEPTABLE]
]], weight = 1 },
    { value = [[
[ETHIC:SLAVERY:PERSONAL_MATTER]
]], weight = 1 },
    { value = [[
[ETHIC:SLAVERY:MISGUIDED]
]], weight = 1 },
    { value = [[
[ETHIC:SLAVERY:APPALLING]
]], weight = 1 },
    { value = [[
[ETHIC:SLAVERY:REQUIRED]
]], weight = 1 },
    { value = [[
[ETHIC:SLAVERY:ONLY_IF_SANCTIONED]
]], weight = 1 },
    { value = [[
[ETHIC:SLAVERY:PUNISH_SERIOUS]
]], weight = 1 },
    { value = [[
[ETHIC:SLAVERY:PUNISH_CAPITAL]
]], weight = 1 }
}


common_data.torture_law = {
    { value = [[	
	[ETHIC:TORTURE_FOR_INFORMATION:ACCEPTABLE]
	[ETHIC:TORTURE_AS_EXAMPLE:ACCEPTABLE]
	[ETHIC:TORTURE_FOR_FUN:PUNISH_SERIOUS]
	[ETHIC:TORTURE_ANIMALS:APPALLING]
]], weight = 1 },
    { value = [[
	[ETHIC:TORTURE_FOR_INFORMATION:ACCEPTABLE]
	[ETHIC:TORTURE_AS_EXAMPLE:ACCEPTABLE]
	[ETHIC:TORTURE_FOR_FUN:PUNISH_REPRIMAND]
	[ETHIC:TORTURE_ANIMALS:APPALLING]
]], weight = 1 },
    { value = [[
	[ETHIC:TORTURE_FOR_INFORMATION:JUSTIFIED_IF_GOOD_REASON]
	[ETHIC:TORTURE_AS_EXAMPLE:JUSTIFIED_IF_GOOD_REASON]
	[ETHIC:TORTURE_FOR_FUN:PUNISH_REPRIMAND]
	[ETHIC:TORTURE_ANIMALS:APPALLING]
]], weight = 1 },
    { value = [[
	[ETHIC:TORTURE_FOR_INFORMATION:ONLY_IF_SANCTIONED]
	[ETHIC:TORTURE_AS_EXAMPLE:ONLY_IF_SANCTIONED]
	[ETHIC:TORTURE_FOR_FUN:PUNISH_REPRIMAND]
	[ETHIC:TORTURE_ANIMALS:APPALLING]
]], weight = 1 },
    { value = [[
	[ETHIC:TORTURE_FOR_INFORMATION:ONLY_IF_SANCTIONED]
	[ETHIC:TORTURE_AS_EXAMPLE:ONLY_IF_SANCTIONED]
	[ETHIC:TORTURE_FOR_FUN:PUNISH_SERIOUS]
	[ETHIC:TORTURE_ANIMALS:APPALLING]
]], weight = 1 }
}



common_data.torture_chaos = {
    { value = [[	
	[ETHIC:TORTURE_FOR_INFORMATION:PERSONAL_MATTER]
	[ETHIC:TORTURE_AS_EXAMPLE:PERSONAL_MATTER]
	[ETHIC:TORTURE_FOR_FUN:APPALLING]
	[ETHIC:TORTURE_ANIMALS:APPALLING]
]], weight = 1 },
    { value = [[
	[ETHIC:TORTURE_FOR_INFORMATION:ACCEPTABLE]
	[ETHIC:TORTURE_AS_EXAMPLE:ACCEPTABLE]
	[ETHIC:TORTURE_FOR_FUN:APPALLING]
	[ETHIC:TORTURE_ANIMALS:APPALLING]
]], weight = 1 },
    { value = [[
	[ETHIC:TORTURE_FOR_INFORMATION:PERSONAL_MATTER]
	[ETHIC:TORTURE_AS_EXAMPLE:PERSONAL_MATTER]
	[ETHIC:TORTURE_FOR_FUN:PERSONAL_MATTER]
	[ETHIC:TORTURE_ANIMALS:PERSONAL_MATTER]
]], weight = 1 },
    { value = [[
	[ETHIC:TORTURE_FOR_INFORMATION:ACCEPTABLE]
	[ETHIC:TORTURE_AS_EXAMPLE:ACCEPTABLE]
	[ETHIC:TORTURE_FOR_FUN:PERSONAL_MATTER]
	[ETHIC:TORTURE_ANIMALS:PERSONAL_MATTER]
]], weight = 1 },
    { value = [[
	[ETHIC:TORTURE_FOR_INFORMATION:ACCEPTABLE]
	[ETHIC:TORTURE_AS_EXAMPLE:ACCEPTABLE]
	[ETHIC:TORTURE_FOR_FUN:ACCEPTABLE]
	[ETHIC:TORTURE_ANIMALS:ACCEPTABLE]
]], weight = 1 }
}


common_data.citysites = {
    { value = [[
	[SELECT_SYMBOL:CIV:NAME_STATE_CITY]
	[DEFAULT_SITE_TYPE:CITY]
	[SELECT_SYMBOL:CIV:NAME_STATE_CITY]
	[LIKES_SITE:CITY]
	[TOLERATES_SITE:CITY]
	[TOLERATES_SITE:CAVE_DETAILED]
	[START_BIOME:ANY_LAND]
	[SETTLEMENT_BIOME:ANY_LAND]
	[BIOME_SUPPORT:ANY_OCEAN:1]
	[BIOME_SUPPORT:ANY_LAKE:1]
	[BIOME_SUPPORT:ANY_RIVER:1]
	[BIOME_SUPPORT:ANY_LAND:10]
	[MAX_STARTING_CIV_NUMBER:1]
	[MAX_POP_NUMBER:10000]
	[MAX_SITE_POP_NUMBER:120]
	[SITE_CONTROLLABLE]
	[OUTDOOR_WOOD]
	[OUTDOOR_FARMING]
	[OUTDOOR_GARDENS][OUTDOOR_ORCHARDS]
	[WORLD_CONSTRUCTION:WALL]
	[WORLD_CONSTRUCTION:BRIDGE]
	[WORLD_CONSTRUCTION:ROAD]
]], weight = 3 },
    { value = [[
	[SELECT_SYMBOL:CIV:NAME_STATE_CITY]
	[DEFAULT_SITE_TYPE:CITY]
	[LIKES_SITE:CITY]
	[TOLERATES_SITE:CITY]
	[TOLERATES_SITE:CAVE_DETAILED]
	[START_BIOME:ANY_LAND]
	[SETTLEMENT_BIOME:ANY_LAND]
	[BIOME_SUPPORT:ANY_OCEAN:10]
	[BIOME_SUPPORT:ANY_LAKE:10]
	[BIOME_SUPPORT:ANY_LAND:1]
	[MAX_STARTING_CIV_NUMBER:1]
	[MAX_POP_NUMBER:10000]
	[MAX_SITE_POP_NUMBER:120]
	[SITE_CONTROLLABLE]
	[OUTDOOR_WOOD]
	[OUTDOOR_FARMING]
	[OUTDOOR_GARDENS][OUTDOOR_ORCHARDS]
	[WORLD_CONSTRUCTION:WALL]
	[WORLD_CONSTRUCTION:BRIDGE]
	[WORLD_CONSTRUCTION:ROAD]
]], weight = 1 },
    { value = [[
	[SELECT_SYMBOL:CIV:NAME_STATE_CITY]
	[DEFAULT_SITE_TYPE:CITY]
	[LIKES_SITE:CITY]
	[TOLERATES_SITE:CITY]
	[TOLERATES_SITE:CAVE_DETAILED]
	[START_BIOME:ANY_LAND]
	[SETTLEMENT_BIOME:ANY_LAND]
	[BIOME_SUPPORT:ANY_WETLAND:10]
	[BIOME_SUPPORT:ANY_LAND:1]
	[MAX_STARTING_CIV_NUMBER:1]
	[MAX_POP_NUMBER:10000]
	[MAX_SITE_POP_NUMBER:120]
	[SITE_CONTROLLABLE]
	[OUTDOOR_WOOD]
	[OUTDOOR_FARMING]
	[OUTDOOR_GARDENS][OUTDOOR_ORCHARDS]
	[WORLD_CONSTRUCTION:WALL]
	[WORLD_CONSTRUCTION:BRIDGE]
	[WORLD_CONSTRUCTION:ROAD]
]], weight = 1 },
    { value = [[
	[SELECT_SYMBOL:CIV:NAME_STATE_CITY]
	[DEFAULT_SITE_TYPE:CITY]
	[LIKES_SITE:CITY]
	[TOLERATES_SITE:CITY]
	[TOLERATES_SITE:CAVE_DETAILED]
	[START_BIOME:ANY_LAND]
	[SETTLEMENT_BIOME:ANY_LAND]
	[BIOME_SUPPORT:MOUNTAIN:10]
	[BIOME_SUPPORT:ANY_LAND:1]
	[MAX_STARTING_CIV_NUMBER:1]
	[MAX_POP_NUMBER:10000]
	[MAX_SITE_POP_NUMBER:120]
	[SITE_CONTROLLABLE]
	[OUTDOOR_WOOD]
	[OUTDOOR_FARMING]
	[OUTDOOR_GARDENS][OUTDOOR_ORCHARDS]
	[WORLD_CONSTRUCTION:WALL]
	[WORLD_CONSTRUCTION:BRIDGE]
	[WORLD_CONSTRUCTION:ROAD]
]], weight = 1 }
}


common_data.hivesites = {
    { value = [[
	[SELECT_SYMBOL:CIV:NAME_STATE_ARCOLOGY]
	[DEFAULT_SITE_TYPE:CAVE_DETAILED]
	[LIKES_SITE:CITY]
	[TOLERATES_SITE:CITY]
	[TOLERATES_SITE:CAVE_DETAILED]
	[EXCLUSIVE_START_BIOME:MOUNTAIN]
	[SETTLEMENT_BIOME:ANY_LAND]
	[SETTLEMENT_BIOME:MOUNTAIN]
	[BIOME_SUPPORT:ANY_LAND:1]
	[BIOME_SUPPORT:MOUNTAIN:10]
	[MAX_STARTING_CIV_NUMBER:1]
	[MAX_POP_NUMBER:10000]
	[MAX_SITE_POP_NUMBER:120]
	[SITE_CONTROLLABLE]
	[MINING_UNDERWORLD_DISASTERS]
	[OUTDOOR_WOOD]
	[INDOOR_FARMING]
	[INDOOR_GARDENS]
	[OUTDOOR_FARMING]
	[WORLD_CONSTRUCTION:TUNNEL]
	[WORLD_CONSTRUCTION:BRIDGE]
	[WORLD_CONSTRUCTION:ROAD]
]], weight = 3 },
    { value = [[
	[SELECT_SYMBOL:CIV:NAME_STATE_CITY]
	[DEFAULT_SITE_TYPE:CAVE_DETAILED]
	[LIKES_SITE:CAVE_DETAILED]
	[TOLERATES_SITE:CITY]
	[TOLERATES_SITE:CAVE_DETAILED]
	[START_BIOME:ANY_LAND]
	[SETTLEMENT_BIOME:ANY_LAND]
	[BIOME_SUPPORT:ANY_LAND:10]
	[MAX_STARTING_CIV_NUMBER:1]
	[MAX_POP_NUMBER:10000]
	[MAX_SITE_POP_NUMBER:120]
	[SITE_CONTROLLABLE]
	[MINING_UNDERWORLD_DISASTERS]
	[OUTDOOR_WOOD]
	[INDOOR_FARMING]
	[INDOOR_GARDENS]
	[OUTDOOR_FARMING]
	[WORLD_CONSTRUCTION:TUNNEL]
	[WORLD_CONSTRUCTION:BRIDGE]
	[WORLD_CONSTRUCTION:ROAD]
]], weight = 1 },
    { value = [[
	[SELECT_SYMBOL:CIV:NAME_STATE_CITY]
	[DEFAULT_SITE_TYPE:CITY]
	[LIKES_SITE:CITY]
	[TOLERATES_SITE:CITY]
	[TOLERATES_SITE:CAVE_DETAILED]
	[START_BIOME:ANY_LAND]
	[SETTLEMENT_BIOME:ANY_LAND]
	[BIOME_SUPPORT:ANY_WETLAND:10]
	[BIOME_SUPPORT:ANY_LAND:1]
	[MAX_STARTING_CIV_NUMBER:1]
	[MAX_POP_NUMBER:10000]
	[MAX_SITE_POP_NUMBER:120]
	[SITE_CONTROLLABLE]
	[OUTDOOR_WOOD]
	[OUTDOOR_FARMING]
	[OUTDOOR_GARDENS][OUTDOOR_ORCHARDS]
	[WORLD_CONSTRUCTION:WALL]
	[WORLD_CONSTRUCTION:BRIDGE]
	[WORLD_CONSTRUCTION:ROAD]
]], weight = 1 },
    { value = [[
	[SELECT_SYMBOL:CIV:NAME_STATE_CITY]
	[DEFAULT_SITE_TYPE:CITY]
	[LIKES_SITE:CITY]
	[TOLERATES_SITE:CITY]
	[TOLERATES_SITE:CAVE_DETAILED]
	[START_BIOME:ANY_LAND]
	[SETTLEMENT_BIOME:ANY_LAND]
	[BIOME_SUPPORT:MOUNTAIN:10]
	[BIOME_SUPPORT:ANY_LAND:1]
	[MAX_STARTING_CIV_NUMBER:1]
	[MAX_POP_NUMBER:10000]
	[MAX_SITE_POP_NUMBER:120]
	[SITE_CONTROLLABLE]
	[OUTDOOR_WOOD]
	[OUTDOOR_FARMING]
	[OUTDOOR_GARDENS][OUTDOOR_ORCHARDS]
	[WORLD_CONSTRUCTION:WALL]
	[WORLD_CONSTRUCTION:BRIDGE]
	[WORLD_CONSTRUCTION:ROAD]
]], weight = 1 }
}


common_data.watersites = {
    { value = [[
	[SELECT_SYMBOL:CIV:NAME_STATE_CITY]
	[DEFAULT_SITE_TYPE:CITY]
	[LIKES_SITE:CITY]
	[TOLERATES_SITE:CITY]
	[TOLERATES_SITE:CAVE_DETAILED]
	[START_BIOME:ANY_LAND]
	[SETTLEMENT_BIOME:ANY_LAND]
	[BIOME_SUPPORT:ANY_OCEAN:10]
	[BIOME_SUPPORT:ANY_LAKE:10]
	[BIOME_SUPPORT:ANY_LAND:1]
	[MAX_STARTING_CIV_NUMBER:1]
	[MAX_POP_NUMBER:10000]
	[MAX_SITE_POP_NUMBER:120]
	[SITE_CONTROLLABLE]
	[OUTDOOR_WOOD]
	[OUTDOOR_FARMING]
	[OUTDOOR_GARDENS][OUTDOOR_ORCHARDS]
	[WORLD_CONSTRUCTION:WALL]
	[WORLD_CONSTRUCTION:BRIDGE]
	[WORLD_CONSTRUCTION:ROAD]
]], weight = 3 },
    { value = [[
	[SELECT_SYMBOL:CIV:NAME_STATE_NETWORK]
	[DEFAULT_SITE_TYPE:CAVE_DETAILED]
	[LIKES_SITE:CAVE_DETAILED]
	[TOLERATES_SITE:CITY]
	[TOLERATES_SITE:CAVE_DETAILED]
	[START_BIOME:ANY_LAND]
	[SETTLEMENT_BIOME:ANY_LAND]
	[BIOME_SUPPORT:ANY_OCEAN:10]
	[BIOME_SUPPORT:ANY_LAKE:10]
	[BIOME_SUPPORT:ANY_LAND:1]
	[MAX_STARTING_CIV_NUMBER:1]
	[MAX_POP_NUMBER:10000]
	[MAX_SITE_POP_NUMBER:120]
	[SITE_CONTROLLABLE]
	[MINING_UNDERWORLD_DISASTERS]
	[OUTDOOR_WOOD]
	[INDOOR_FARMING]
	[INDOOR_GARDENS]
	[OUTDOOR_FARMING]
	[WORLD_CONSTRUCTION:TUNNEL]
	[WORLD_CONSTRUCTION:BRIDGE]
	[WORLD_CONSTRUCTION:ROAD]
]], weight = 1 }
}


common_data.cavesites = {
    { value = [[
	[SELECT_SYMBOL:CIV:NAME_STATE_SANCTUARY]
	[DEFAULT_SITE_TYPE:CAVE]
	[LIKES_SITE:CAVE_DETAILED]
	[TOLERATES_SITE:CITY]
	[TOLERATES_SITE:CAVE_DETAILED]
	[START_BIOME:ANY_LAND]
	[BIOME_SUPPORT:ANY_LAND:10]
	[MAX_STARTING_CIV_NUMBER:1]
	[MAX_POP_NUMBER:10000]
	[MAX_SITE_POP_NUMBER:120]
	[LOCAL_BANDITRY]
	[OUTDOOR_WOOD]
	[INDOOR_FARMING]
	[INDOOR_GARDENS]
	[OUTDOOR_FARMING]
	[BABYSNATCHER]
	[ITEM_THIEF]
]], weight = 1 }
}

common_data.tribesites = {
    { value = [[
	[SELECT_SYMBOL:CIV:NAME_STATE_SANCTUARY]
	[DEFAULT_SITE_TYPE:CAVE]
	[LIKES_SITE:CAVE_DETAILED]
	[TOLERATES_SITE:CITY]
	[TOLERATES_SITE:CAVE_DETAILED]
	[START_BIOME:ANY_LAND]
	[BIOME_SUPPORT:ANY_LAND:10]
	[MAX_STARTING_CIV_NUMBER:1]
	[MAX_POP_NUMBER:10000]
	[MAX_SITE_POP_NUMBER:120]
	[SITE_CONTROLLABLE]
	[OUTDOOR_WOOD]
	[INDOOR_FARMING]
	[INDOOR_GARDENS]
	[OUTDOOR_FARMING]
	[BABYSNATCHER]
]], weight = 3 },
    { value = [[
	[SELECT_SYMBOL:CIV:NAME_STATE_HIVE]
	[DEFAULT_SITE_TYPE:CAVE_DETAILED]
	[LIKES_SITE:CAVE_DETAILED]
	[TOLERATES_SITE:CITY]
	[TOLERATES_SITE:CAVE_DETAILED]
	[START_BIOME:ANY_DESERT]
	[SETTLEMENT_BIOME:ANY_LAND]
	[BIOME_SUPPORT:ANY_LAND:10]
	[MAX_STARTING_CIV_NUMBER:1]
	[MAX_POP_NUMBER:10000]
	[MAX_SITE_POP_NUMBER:120]
	[LOCAL_BANDITRY]
	[MINING_UNDERWORLD_DISASTERS]
	[OUTDOOR_WOOD]
	[INDOOR_FARMING]
	[INDOOR_GARDENS]
	[OUTDOOR_FARMING]
	[WORLD_CONSTRUCTION:TUNNEL]
	[WORLD_CONSTRUCTION:BRIDGE]
	[WORLD_CONSTRUCTION:ROAD]
	[BABYSNATCHER]
]], weight = 1 }
}


common_data.spacersites = {
    { value = [[	
	[SELECT_SYMBOL:CIV:NAME_STATE_ARCOLOGY]
	[DEFAULT_SITE_TYPE:CAVE_DETAILED]
	[LIKES_SITE:CITY]
	[TOLERATES_SITE:CITY]
	[TOLERATES_SITE:CAVE_DETAILED]
	[EXCLUSIVE_START_BIOME:MOUNTAIN]
	[SETTLEMENT_BIOME:ANY_LAND]
	[SETTLEMENT_BIOME:MOUNTAIN]
	[BIOME_SUPPORT:ANY_LAND:1]
	[BIOME_SUPPORT:MOUNTAIN:10]
	[MAX_STARTING_CIV_NUMBER:1]
	[MAX_POP_NUMBER:10000]
	[MAX_SITE_POP_NUMBER:120]
	[SITE_CONTROLLABLE]
	[MINING_UNDERWORLD_DISASTERS]
	[OUTDOOR_WOOD]
	[INDOOR_FARMING]
	[INDOOR_GARDENS]
	[OUTDOOR_FARMING]
	[WORLD_CONSTRUCTION:TUNNEL]
	[WORLD_CONSTRUCTION:BRIDGE]
	[WORLD_CONSTRUCTION:ROAD]
]], weight = 3 },
    { value = [[
	[SELECT_SYMBOL:CIV:NAME_STATE_NETWORK]
	[DEFAULT_SITE_TYPE:CAVE_DETAILED]
	[LIKES_SITE:CAVE_DETAILED]
	[TOLERATES_SITE:CITY]
	[TOLERATES_SITE:CAVE_DETAILED]
	[START_BIOME:ANY_LAND]
	[SETTLEMENT_BIOME:ANY_LAND]
	[BIOME_SUPPORT:ANY_LAND:10]
	[MAX_STARTING_CIV_NUMBER:1]
	[MAX_POP_NUMBER:10000]
	[MAX_SITE_POP_NUMBER:120]
	[SITE_CONTROLLABLE]
	[MINING_UNDERWORLD_DISASTERS]
	[OUTDOOR_WOOD]
	[INDOOR_FARMING]
	[INDOOR_GARDENS]
	[OUTDOOR_FARMING]
	[WORLD_CONSTRUCTION:TUNNEL]
	[WORLD_CONSTRUCTION:BRIDGE]
	[WORLD_CONSTRUCTION:ROAD]
]], weight = 1 },
    { value = [[
	[SELECT_SYMBOL:CIV:NAME_STATE_NETWORK]
	[DEFAULT_SITE_TYPE:CAVE_DETAILED]
	[LIKES_SITE:CAVE_DETAILED]
	[TOLERATES_SITE:CITY]
	[TOLERATES_SITE:CAVE_DETAILED]
	[START_BIOME:ANY_LAND]
	[SETTLEMENT_BIOME:ANY_LAND]
	[BIOME_SUPPORT:ANY_OCEAN:10]
	[BIOME_SUPPORT:ANY_LAKE:10]
	[BIOME_SUPPORT:ANY_LAND:1]
	[MAX_STARTING_CIV_NUMBER:1]
	[MAX_POP_NUMBER:10000]
	[MAX_SITE_POP_NUMBER:120]
	[SITE_CONTROLLABLE]
	[MINING_UNDERWORLD_DISASTERS]
	[OUTDOOR_WOOD]
	[INDOOR_FARMING]
	[INDOOR_GARDENS]
	[OUTDOOR_FARMING]
	[WORLD_CONSTRUCTION:TUNNEL]
	[WORLD_CONSTRUCTION:BRIDGE]
	[WORLD_CONSTRUCTION:ROAD]
]], weight = 1 }
}


common_data.outersites = {
    { value = [[	
	[SELECT_SYMBOL:CIV:NAME_STATE_ARCOLOGY]
	[DEFAULT_SITE_TYPE:CAVE_DETAILED]
	[LIKES_SITE:CITY]
	[TOLERATES_SITE:CITY]
	[TOLERATES_SITE:CAVE_DETAILED]
	[EXCLUSIVE_START_BIOME:MOUNTAIN]
	[SETTLEMENT_BIOME:ANY_LAND]
	[SETTLEMENT_BIOME:MOUNTAIN]
	[BIOME_SUPPORT:ANY_LAND:1]
	[BIOME_SUPPORT:MOUNTAIN:10]
	[MAX_STARTING_CIV_NUMBER:1]
	[MAX_POP_NUMBER:10000]
	[MAX_SITE_POP_NUMBER:120]
	[SITE_CONTROLLABLE]
	[MINING_UNDERWORLD_DISASTERS]
	[OUTDOOR_WOOD]
	[INDOOR_FARMING]
	[INDOOR_GARDENS]
	[OUTDOOR_FARMING]
	[WORLD_CONSTRUCTION:TUNNEL]
	[WORLD_CONSTRUCTION:BRIDGE]
	[WORLD_CONSTRUCTION:ROAD]
]], weight = 3 },
    { value = [[
	[SELECT_SYMBOL:CIV:NAME_STATE_NETWORK]
	[DEFAULT_SITE_TYPE:CAVE_DETAILED]
	[LIKES_SITE:CAVE_DETAILED]
	[TOLERATES_SITE:CITY]
	[TOLERATES_SITE:CAVE_DETAILED]
	[START_BIOME:ANY_LAND]
	[SETTLEMENT_BIOME:ANY_LAND]
	[BIOME_SUPPORT:ANY_LAND:10]
	[MAX_STARTING_CIV_NUMBER:1]
	[MAX_POP_NUMBER:10000]
	[MAX_SITE_POP_NUMBER:120]
	[SITE_CONTROLLABLE]
	[MINING_UNDERWORLD_DISASTERS]
	[OUTDOOR_WOOD]
	[INDOOR_FARMING]
	[INDOOR_GARDENS]
	[OUTDOOR_FARMING]
	[WORLD_CONSTRUCTION:TUNNEL]
	[WORLD_CONSTRUCTION:BRIDGE]
	[WORLD_CONSTRUCTION:ROAD]
]], weight = 1 },
    { value = [[
	[SELECT_SYMBOL:CIV:NAME_STATE_HIVE]
	[DEFAULT_SITE_TYPE:CAVE_DETAILED]
	[LIKES_SITE:CAVE_DETAILED]
	[TOLERATES_SITE:CITY]
	[TOLERATES_SITE:CAVE_DETAILED]
	[START_BIOME:ANY_DESERT]
	[SETTLEMENT_BIOME:ANY_LAND]
	[BIOME_SUPPORT:ANY_LAND:10]
	[MAX_STARTING_CIV_NUMBER:1]
	[MAX_POP_NUMBER:10000]
	[MAX_SITE_POP_NUMBER:120]
	[SITE_CONTROLLABLE]
	[MINING_UNDERWORLD_DISASTERS]
	[OUTDOOR_WOOD]
	[INDOOR_FARMING]
	[INDOOR_GARDENS]
	[OUTDOOR_FARMING]
	[WORLD_CONSTRUCTION:TUNNEL]
	[WORLD_CONSTRUCTION:BRIDGE]
	[WORLD_CONSTRUCTION:ROAD]
]], weight = 1 }
}


common_data.evilsites = {
    { value = [[		
	[SELECT_SYMBOL:CIV:NAME_STATE_NEXUS]
	[DEFAULT_SITE_TYPE:DARK_FORTRESS]
	[LIKES_SITE:DARK_FORTRESS]
	[TOLERATES_SITE:CITY]
	[TOLERATES_SITE:CAVE_DETAILED]
	[START_BIOME:ANY_LAND]
	[SETTLEMENT_BIOME:ANY_LAND]
	[BIOME_SUPPORT:ANY_LAND:1]
	[MAX_STARTING_CIV_NUMBER:0]
	[MAX_POP_NUMBER:10000]
	[MAX_SITE_POP_NUMBER:120]
	[OUTDOOR_WOOD]
	[INDOOR_WOOD]
	[INDOOR_FARMING]
	[INDOOR_GARDENS]
	[OUTDOOR_FARMING]
	[WORLD_CONSTRUCTION:TUNNEL]
	[WORLD_CONSTRUCTION:BRIDGE]
	[WORLD_CONSTRUCTION:ROAD]
]], weight = 1 }
}

common_data.monosites = {
    { value = [[			
	[SELECT_SYMBOL:CIV:NAME_STATE_CITADEL]
	[DEFAULT_SITE_TYPE:CAVE_DETAILED]
	[LIKES_SITE:CITY]
	[TOLERATES_SITE:CITY]
	[TOLERATES_SITE:CAVE_DETAILED]
	[EXCLUSIVE_START_BIOME:ANY_LAND]
	[EXCLUSIVE_START_BIOME:MOUNTAIN]
	[BIOME_SUPPORT:ANY_LAND:10]
	[BIOME_SUPPORT:ANY_OCEAN:10]
	[BIOME_SUPPORT:MOUNTAIN:10]
	[SITE_CONTROLLABLE]
	[MINING_UNDERWORLD_DISASTERS]
	[OUTDOOR_WOOD]
	[INDOOR_FARMING]
	[INDOOR_GARDENS]
	[OUTDOOR_FARMING]
	[WORLD_CONSTRUCTION:TUNNEL]
	[WORLD_CONSTRUCTION:BRIDGE]
	[WORLD_CONSTRUCTION:ROAD]
]], weight = 1 },
    { value = [[			
	[SELECT_SYMBOL:CIV:NAME_STATE_TOWN]
	[DEFAULT_SITE_TYPE:CITY]
	[LIKES_SITE:CITY]
	[TOLERATES_SITE:CITY]
	[TOLERATES_SITE:CAVE_DETAILED]
	[EXCLUSIVE_START_BIOME:ANY_LAND]
	[EXCLUSIVE_START_BIOME:MOUNTAIN]
	[BIOME_SUPPORT:ANY_LAKE:10]
	[BIOME_SUPPORT:ANY_OCEAN:10]
	[BIOME_SUPPORT:ANY_LAND:1]
	[BIOME_SUPPORT:MOUNTAIN:1]
	[SITE_CONTROLLABLE]
	[OUTDOOR_WOOD]
	[INDOOR_FARMING]
	[INDOOR_GARDENS]
	[OUTDOOR_FARMING]
	[WORLD_CONSTRUCTION:WALL]
	[WORLD_CONSTRUCTION:BRIDGE]
	[WORLD_CONSTRUCTION:ROAD]
]], weight = 4 }
}

common_data.monosites_fort = {
    { value = [[			
	[SELECT_SYMBOL:CIV:NAME_STATE_CITADEL]
	[DEFAULT_SITE_TYPE:CAVE_DETAILED]
	[LIKES_SITE:CITY]
	[TOLERATES_SITE:CITY]
	[TOLERATES_SITE:CAVE_DETAILED]
	[EXCLUSIVE_START_BIOME:ANY_LAND]
	[EXCLUSIVE_START_BIOME:MOUNTAIN]
	[BIOME_SUPPORT:ANY_LAND:10]
	[BIOME_SUPPORT:ANY_OCEAN:10]
	[BIOME_SUPPORT:MOUNTAIN:10]
	[SITE_CONTROLLABLE]
	[MINING_UNDERWORLD_DISASTERS]
	[OUTDOOR_WOOD]
	[INDOOR_FARMING]
	[INDOOR_GARDENS]
	[OUTDOOR_FARMING]
	[WORLD_CONSTRUCTION:TUNNEL]
	[WORLD_CONSTRUCTION:BRIDGE]
	[WORLD_CONSTRUCTION:ROAD]
]], weight = 1 }
}



common_data.shield_all = {
    { value = [[	
	[SHIELD:ITEM_SHIELD_ULTRALIGHT_SLD]
	[SHIELD:ITEM_SHIELD_LIGHT_SLD]
	[SHIELD:ITEM_SHIELD_MEDIUM_SLD]
	[SHIELD:ITEM_SHIELD_HEAVY_SLD]
	[SHIELD:ITEM_SHIELD_SUPERHEAVY_SLD]
]], weight = 1 },
    { value = [[
	[SHIELD:ITEM_SHIELD_ULTRALIGHT_ABL]
	[SHIELD:ITEM_SHIELD_LIGHT_ABL]
	[SHIELD:ITEM_SHIELD_MEDIUM_ABL]
	[SHIELD:ITEM_SHIELD_HEAVY_ABL]
	[SHIELD:ITEM_SHIELD_SUPERHEAVY_ABL]
]], weight = 1 },
    { value = [[
	[SHIELD:ITEM_SHIELD_ULTRALIGHT_ERA]
	[SHIELD:ITEM_SHIELD_LIGHT_ERA]
	[SHIELD:ITEM_SHIELD_MEDIUM_ERA]
	[SHIELD:ITEM_SHIELD_HEAVY_ERA]
	[SHIELD:ITEM_SHIELD_SUPERHEAVY_ERA]
]], weight = 1 },
    { value = [[	
	[SHIELD:ITEM_SHIELD_ULTRALIGHT_ENR]
	[SHIELD:ITEM_SHIELD_LIGHT_ENR]
	[SHIELD:ITEM_SHIELD_MEDIUM_ENR]
	[SHIELD:ITEM_SHIELD_HEAVY_ENR]
	[SHIELD:ITEM_SHIELD_SUPERHEAVY_ENR]
]], weight = 1 },
    { value = [[
	[SHIELD:ITEM_SHIELD_ULTRALIGHT_HDL]
	[SHIELD:ITEM_SHIELD_LIGHT_HDL]
	[SHIELD:ITEM_SHIELD_MEDIUM_HDL]
	[SHIELD:ITEM_SHIELD_HEAVY_HDL]
	[SHIELD:ITEM_SHIELD_SUPERHEAVY_HDL]
]], weight = 1 }
}

common_data.shield_low = {
    { value = [[	
	[SHIELD:ITEM_SHIELD_ULTRALIGHT_SLD]
	[SHIELD:ITEM_SHIELD_LIGHT_SLD]
	[SHIELD:ITEM_SHIELD_MEDIUM_SLD]
	[SHIELD:ITEM_SHIELD_HEAVY_SLD]
	[SHIELD:ITEM_SHIELD_SUPERHEAVY_SLD]
]], weight = 1 },
    { value = [[
	[SHIELD:ITEM_SHIELD_ULTRALIGHT_ABL]
	[SHIELD:ITEM_SHIELD_LIGHT_ABL]
	[SHIELD:ITEM_SHIELD_MEDIUM_ABL]
	[SHIELD:ITEM_SHIELD_HEAVY_ABL]
	[SHIELD:ITEM_SHIELD_SUPERHEAVY_ABL]
]], weight = 1 },
    { value = [[
	[SHIELD:ITEM_SHIELD_ULTRALIGHT_ERA]
	[SHIELD:ITEM_SHIELD_LIGHT_ERA]
	[SHIELD:ITEM_SHIELD_MEDIUM_ERA]
	[SHIELD:ITEM_SHIELD_HEAVY_ERA]
	[SHIELD:ITEM_SHIELD_SUPERHEAVY_ERA]
]], weight = 1 }
}

common_data.shield_high = {
    { value = [[	
	[SHIELD:ITEM_SHIELD_ULTRALIGHT_ENR]
	[SHIELD:ITEM_SHIELD_LIGHT_ENR]
	[SHIELD:ITEM_SHIELD_MEDIUM_ENR]
	[SHIELD:ITEM_SHIELD_HEAVY_ENR]
	[SHIELD:ITEM_SHIELD_SUPERHEAVY_ENR]
]], weight = 1 },
    { value = [[
	[SHIELD:ITEM_SHIELD_ULTRALIGHT_HDL]
	[SHIELD:ITEM_SHIELD_LIGHT_HDL]
	[SHIELD:ITEM_SHIELD_MEDIUM_HDL]
	[SHIELD:ITEM_SHIELD_HEAVY_HDL]
	[SHIELD:ITEM_SHIELD_SUPERHEAVY_HDL]
]], weight = 1 }
}

common_data.shield_holo = {
    { value = [[
	[SHIELD:ITEM_SHIELD_ULTRALIGHT_HDL]
	[SHIELD:ITEM_SHIELD_LIGHT_HDL]
	[SHIELD:ITEM_SHIELD_MEDIUM_HDL]
	[SHIELD:ITEM_SHIELD_HEAVY_HDL]
	[SHIELD:ITEM_SHIELD_SUPERHEAVY_HDL]
]], weight = 1 }
}

return {
    common_data = common_data
}
